- README.md
- script/DeployMigrationNFT.s.sol
- src/bridge/MigrationNFT.sol
- test/bridge/MigrationNFT.sol
- **change meta**
- **introduce notion of levels and different token URIs**
- **move to a soulbound token**
- **remove unused batch**
- **holder limitation still allows for level ups**
- **integrate levels**
- **update deploy script**
> modify bridging nft to be soulbound and levels based

- src/Rewards.sol
- test/Rewards.t.sol
In this implementation I have defined the struct BatchReward as:
```
struct BatchReward {
address[] recipients;
uint256[] amounts;
uint256 sequence;
}
```
assuming `recipients[i]` corresponds to `amounts[i]`. This means we expect `recipients.length == amounts.length`. That's why `mintBatchReward` needed to check this assumption. The reason I have gone for this design was to avoid using **nested types** which could make `digestReward` more complicated and costly. `digestReward` is needed for checking the signature.
> feat(Rewards): add mintBatchReward

- .devcontainer/Dockerfile
Build from `dev` every week is no longer the best idea as it introduces a number of bugs and breaking changes which hurts productivity and determinism for the team. So far we have had good results with the version under commit `33b81acf8688f8cc1fc839b7e4a07ec58b347cb4` and I suggest we stick to it until we have a strong reasoning to upgrade, or until a stable version is published.
> freeze forge in devcontainer to known good commit

- script/DeployNodlMigration.sol
- script/DeployRewards.sol
NOTE 1: The forge script cannot proceed to successful deployment and hangs on:
```
Script ran successfully.
== Logs ==
Deployed Rewards at 0x19610AF1045b349acEAE83c6239a5B13e567D612
==========================
Chain 300
Estimated gas price: 3.05 gwei
Estimated total gas used for script: 772607094
Estimated amount required: 2.3564516367 ETH
==========================
###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 1].
⠉ [00:00:01] [####################################################################################################################] 2/2 txes (0.0s)
Transactions saved to: /workspaces/rollup/broadcast/DeployRewards.sol/300/run-latest.json
Sensitive values saved to: /workspaces/rollup/cache/DeployRewards.sol/300/run-latest.json
##
Waiting for …
```
> feat(Rewards): add deploy script

- src/Grants.sol
- src/Rewards.sol
- test/Grants.t.sol
- test/Rewards.t.sol
Implement this contract to present similar but improved logic compared with pallet-grants on Eden parachain. Here is a couple of differences:
1. No admin or high level access is required. In pallet-grants the governance could cancel grants for anyone (not renounced) but this was too much unwarranted power. This contract allows any vesters to cancel their unvested grants if they have not renounced this authority towards a specific address.
2. Instead of unfriendly block numbers, here we use time stamps.
3. This contract would work with any standard Erc20 token and not just Nodl.
> feat(Grants): Implement Nodl Grants on ZkSync

- src/bridge/BridgeBase.sol
- src/bridge/GrantsMigration.sol
- test/bridge/GrantsMigration.t.sol
This contract is zksync side of the bridge from Eden Parachain. The tokens minted here are already burnt on the side of parachain. The implementation follows the same logic as we have had for the migration of free NODL tokens (NODLMigration). 
The known limitation of this implementation is that if an oracle creates a vote with wrong parameters the consensus of other oracles can not fix the proposal. This is not expected to happen with our permissioned oracles. But in the worst case scenario, if the bridge doesn't proceed for a proposal, the governance needs to intervene. Until that no unintended consequence is expected.
> feat(GrantsMigration): allow permissioned off chain oracles to mint tokens and lock them for grants

- script/DeployRewards.sol
- src/Rewards.sol
- test/Rewards.t.sol
Correct a mistake in sanitizing `batchSubmitterRewardPercentage`. Plus reduce the storage requirement for that variable.
> fix(Rewards): correct range check

- src/Grants.sol
- test/Grants.t.sol
- test/bridge/GrantsMigration.t.sol
Introduce minimum for perPeriodAmount. Since for different ERC20 tokens, the dust threshold could be different, let this minimum be adjustable during the deployment.
> feat(Grants): make spamming costly 

- src/Rewards.sol
- test/Rewards.t.sol
This is needed for our backend to easily enquire which of the issued batch rewards got on chain successfully
> feat(Rewards): remember the latest batch digest

- src/Grants.sol
- test/Grants.t.sol
- test/bridge/GrantsMigration.t.sol
Rmove the maximum grants limit which could create undesired consequences when an address is spammed. However we need to paginate the storage to keep the cost of iterating over all the grants for functions like claim, cancel and renounce limited and predictable. For convenience of the contract users we assume startPage == endPage == 0 means iterate over all the pages (which could make sense if the user already knows this wouldn't be too expensive.
**NOTE:** we are not defragmenting the storage when some schedules are removed from a page. This means the number of items in every page would be variable but always less than or equal the pageLimit.
> feat(Grants): paginate storage and remove max grant limit

- script/DeployClick.s.sol
- script/DeployContentSignEnterprise.s.sol
- script/DeployNodlMigration.sol
- script/DeployRewards.sol
- src/NODL.sol
- src/Rewards.sol
- src/contentsign/EnterpriseContentSign.sol
- src/paymasters/WhitelistPaymaster.sol
- test/NODL.t.sol
- test/Rewards.t.sol
- test/bridge/GrantsMigration.t.sol
- test/bridge/MigrationNFT.t.sol
- test/bridge/NODLMigration.t.sol
- test/contentsign/ClickContentSign.t.sol
- test/contentsign/EnterpriseContentSign.t.sol
- test/paymasters/WhitelistPaymaster.t.sol
Assign admin privileges to a designated multi-signature (multi-sig) or governance-controlled address during deployment rather than granting these privileges to the deployer. This approach reduces the risk of a single point of failure associated with the deployer’s private key.
> feat: separate deployer and admin roles

- src/Rewards.sol
- test/Rewards.t.sol
Add a setter method similar to the existing setQuota function, allowing the DEFAULT_ADMIN_ROLE user to adjust the period.
> feat(Rewards): allow period to be changed by admin

- .cspell.json
- .github/workflows/checks.yml
- README.md
- hardhat.config.ts
- src/Grants.sol
- src/Rewards.sol
- src/bridge/BridgeBase.sol
- src/bridge/MigrationNFT.sol
- src/bridge/NODLMigration.sol
- subquery/README.md
- subquery/src/utils/utils.ts
- test/Grants.t.sol
- test/Rewards.t.sol
- test/bridge/MigrationNFT.t.sol
“observations” are any comment or recommendation about code quality or security best practices that are unlikely to pose an immediate and exploitable risk to the assets within the security review’s scope. However we have tried to address as many of them as possible in this PR.
> Address matterlabs audit observations

- src/Grants.sol
Check-Effects-Interaction pattern suggests it's even safer for the events to be called before any interactions.
> chore(Grants): emit event before intraction

- clk-gateway/src/index.ts
- clk-gateway/src/interfaces.ts
Attempts to decode the smart contract revert reason to return 4xx when possible.
> feat(clk-gateway): prefer 4xx over 5xx when error is parsable

- src/contentsign/PaymentMiddleware.sol
- test/contentsign/PaymentMiddleware.t.sol
As per https://www.notion.so/nodle/Token-payments-for-Click-proof-of-provenance-1837133336d480ecb2dafa5e44497bb5?pvs=4
> add middleware contract

- src/contentsign/ClickBounty.sol
- test/contentsign/ClickBounty.t.sol
Allows a prize pool for click tokens to form and to pay.
> feat(ClickBounty): enter a pool and be into win

- .gitignore
- remappings.txt
- script/DeployMigrationNFT.s.sol
- src/Grants.sol
- src/NODL.sol
- src/Payment.sol
- src/QuotaControl.sol
- src/Rewards.sol
- src/bridge/MigrationNFT.sol
- src/contentsign/BaseContentSign.sol
- src/contentsign/EnterpriseContentSign.sol
- src/contentsign/PaymentMiddleware.sol
- src/nameservice/ClickNameService.sol
- src/nameservice/ClickResolver.sol
- src/paymasters/BasePaymaster.sol
- test/NODL.t.sol
- test/Rewards.t.sol
- test/__helpers__/AccessControlUtils.sol
- test/bridge/GrantsMigration.t.sol
- test/bridge/MigrationNFT.t.sol
- test/bridge/NODLMigration.t.sol
Enabling both forge and hardhat builds and addressing some warnings
> Consistent openzeppelin imports

- deploy/click_bounty.dp.ts
- hardhat.config.ts
Also allow hardhat config to have ETHERSCAN_API_KEY to verify contract. This deployment script used to deploy https://sepolia-era.zksync.network/address/0x6aac68102f9096d42aB302cc6b66Dd57CE7b1E79#code
> chore: add deploy script for ClickBounty

- clk-gateway/src/helpers.ts
- clk-gateway/src/index.ts
- clk-gateway/src/interfaces.ts
* Added AbiCoder import in helpers.ts.
* Introduced new constants for commit ABI and stored batch in interfaces.ts.
* Improved parseCommitTransaction function to handle transaction errors not found.
* Added validations for the “sender” parameter in the /storageProof path in index.ts.
* Removed unnecessary whitespace in several functions.
> Update /storageProof helpers - adapted them to latest changes on root contract
